### ISSUE TITLE
IOS only?

### ISSUE THREAD

**Issue by ababkov** [Thinkmill/react-conf-app#11]
Are you submitting to Google play?

**Comment by blargity** [comment]
We are absolutely planning on supporting Android and submitting to Google Play.

There are still some rough edges on Android which we're going to be focusing on fixing up today. Of course PRs are welcome as well!

**Comment by ababkov** [comment]
@blargity Any chance you have an issues list or is it a "test and patch what you can" kind of situation.

**Comment by blargity** [comment]
We don't have an active list right now, it's more "Fix the stuff that you know doesn't work already just by running it on a phone".

I'll make sure that at the end of the day whatever's outstanding we log as issues here. That should make it more transparent for people to contribute fixes back if they're keen!

**Comment by blargity** [comment]
@ababkov, the issue list here should be up to date with the current state of play on android now. Feel free to let me know if you have any questions or if there's a specific issue you'd like to take ownership of. PRs to help us move faster on this would be awesome!

**Comment by ababkov** [comment]
@blargity was going to jump on but had some issues getting the android version to build. Wouldn't mind just exploring now that you've fixed most of the issues ;) - any tips on getting it running beyond `react-native run-android`. It currently terminates with:

```
/.../react-conf-app/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:32:28-55: AAPT: No resource found that matches the given name (at 'value' with value '@string/google_maps_api_key').

/.../react-conf-app/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:30: error: Error: No resource found that matches the given name (at 'value' with value '@string/google_maps_api_key').

FAILURE: Build failed with an exception.
```

**Comment by blargity** [comment]
@ababkov No worries! Yeah, we haven't documented that yet, sorry for the trouble. I'll add steps to the readme.

The reason the build is failing on Android is because it needs a Google Maps API key for the map component. You can [go to this page](https://developers.google.com/maps/documentation/android-api/signup) to get one.

Once you've got one, create a file in `android/app/src/main/res/values` called `google_maps_api_key.xml` and put these contents in:

```
<resources>
    <string name="google_maps_api_key">[The Google Maps API Key Here]</string>
</resources>
```

You should then be able to `react-native run-android`.
