### ISSUE TITLE
Transition animation glitch

### ISSUE THREAD

**Issue by edwinbosire** [Thinkmill/react-conf-app#13]
There's a slight transition animation glitch when viewing the info page.
From experience, it seems to be an Xcode 8 + iOS 10 combo thing. 

The two errors from Xcode are pasted below. 

`ERROR /BuildRoot/Library/Caches/com.apple.xbs/Sources/VectorKit_Sim/VectorKit-1230.32.8.29.9/GeoGL/GeoGL/GLCoreContext.cpp 1764: WARNING: Output of vertex shader 'v_gradient' not read by fragment shader`

`ERROR /BuildRoot/Library/Caches/com.apple.xbs/Sources/VectorKit_Sim/VectorKit-1230.32.8.29.9/GeoGL/GeoGL/GLCoreContext.cpp 1763: InfoLog SolidRibbonShader:`

Rumour has it that these two errors are only present in the simulator or debug builds, but not so in the production/release builds. ¯\_(ツ)_/¯

**Comment by export-mike** [comment]
Hey @edwinbosire its been awhile! hope your well!

Yes your right about the rumour, it runs a lot smoother when the app is built for release

**Comment by export-mike** [comment]
We're all in agreement this is a debug error, so closing the issue

**Comment by kalpeshjjethva** [comment]
@edwinbosire  have you found any solutions? 'v_gradient'
