### ISSUE TITLE
Timezone problem

### ISSUE THREAD

**Issue by brunolemos** [Thinkmill/react-conf-app#47]
The app is considering my phone timezone instead of the one the React Conf is on.
So the schedule is marking lots of items as already happened, which is not true.

**Comment by blargity** [comment]
Hi @brunolemos,

You're absolutely right, the app assumes you're going to be in SF for the conference, and that your phone will be set to that timezone. It's just using `new Date()` to figure out what time it is.

It's something we considered but figured was an edge case that we wouldn't support for launch. We'd be happy to look at PRs that would change this, but haven't prioritised it on our own.
