### ISSUE TITLE
How did you do the background pattern on <Break /> component

### ISSUE THREAD

**Issue by vko-online** [Thinkmill/react-conf-app#54]
How this was done?
![pattern](http://dl3.joxi.net/drive/2017/05/14/0021/1472/1410496/96/c2c4afe1cc.png)

Altho the project is open sourced (huge thanks to you guys) the [exponent version](https://expo.io/@community/reactconf2017) differs from this source, this source doesnt have that pattern
Is it an image background? Or linear-gradient?

**Comment by blargity** [comment]
I can see why you're having trouble locating it in the code. The last version of the app changed this styling.

It was done with a gradient, but heads up, that didn't work on Android.

Here's the relevant version with the gradient code still in: https://github.com/Thinkmill/react-conf-app/blob/c5571ed895da86e9fe23117b40165dc160494ac1/app/scenes/Schedule/components/Break/index.js

**Comment by nzmedet** [comment]
In the App-store version, app doesn't correctly render TalkPreviewNext, TalkPreviewPrev components

They typically doesn't show up after viewing a talk

Would you consider updating app in appstore?
